# Generated by Django 5.0.4 on 2024-04-20 08:36

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[main.models.validate_no_digits], verbose_name='Название:')),
                ('small_text', models.TextField(max_length=50, verbose_name='Краткое описание:')),
                ('category', models.CharField(max_length=50, validators=[main.models.validate_no_digits], verbose_name='Категория:')),
                ('full_text', models.TextField(max_length=200, verbose_name='Развернутое описание:')),
                ('count_of', models.IntegerField(verbose_name='Количество товаров на складе:')),
                ('price', models.FloatField(max_length=10, verbose_name='Цена:')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий:')),
                ('date', models.DateTimeField(verbose_name='Дата публикации:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_comment', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.productimage'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='Оценка:')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='main.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_word', models.TextField(blank=True, max_length=20, verbose_name='Кодовое слово:')),
                ('role', models.CharField(blank=True, default='user', max_length=20, verbose_name='Роль:')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Введите ваш город:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
