# Generated by Django 5.0.4 on 2024-04-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_text',
            field=models.TextField(max_length=2000, verbose_name='Развернутое описание:'),
        ),
    ]
